#!/usr/bin/node
var gitRunner = require('./runner');
gitRunner.run({
  command: process.argv[2],
  repoName: process.argv[3],
  username: process.argv[4],
  beforeCommit: process.argv[5],
  afterCommit: process.argv[6]
}, process.stdin);
