#!/usr/bin/ruby
require 'net/http'

require 'rubygems'
require 'json'

# command line
@command = ARGV[0]
case @command
when 'read'
  @repo_name = ARGV[1]
  @username = ARGV[2]
when 'write'
  @repo_name = ARGV[1]
  @username = ARGV[3]
end

# Request details
@host = "doskara.herokuapp.com"
@port = 80
@url = '/repositories/canpush.json'
@payload = {
  "repository" => {
    "name" => @repo_name,
    "username" => @username
  }
}.to_json

# definition of a json request
def post
  req = Net::HTTP::Post.new(@url, initheader = {'Content-Type' => 'application/json'})
  req.body = @payload
  response = Net::HTTP.new(@host, @port).start {|http| http.request(req)}
  JSON.parse(response.body)
end

# handle response
response = post
if response['success']
  exit 0
elsif response['error'] == 'InvalidRepository'
  exit 1
elsif response['error'] == 'NoAccess'
  exit 2
else
  exit 3
end
